language: python

python:
- "2.7"
- "3.4"

before_install:
- sudo apt-get update
- sudo apt-get -y install libmumps-seq-dev coinor-libclp-dev coinor-libcbc-dev coinor-libipopt-dev

install: 
- pip install -r requirements.txt

script:
- python setup.py build_ext --inplace --with "mumps clp cbc ipopt" --libraries "dmumps_seq Clp Cbc Ipopt"
- nosetests -s -v