language: python

before_install:
- sudo apt-get update
- sudo apt-get -y install libmumps-seq-dev

install: 
- pip install nose numpy dill 
- pip install scipy 
- python -c "import scipy"
- python -c "import scipy.sparse"
- pip install cython 
- python -c "import Cython"
- python -c "import cython"

script:
- python setup.py build_ext --inplace --no_ipopt
- nosetests -s -v