language: python

install: 
- sudo apt-get update
- sudo apt-get -y install libmumps-seq-dev
- sudo pip install nose numpy scipy cython dill
- python -c "import scipy"
- python -c "import scipy.sparse"
- python -c "import Cython"
- python -c "import cython"

script:
- python setup.py build_ext --inplace --no_ipopt
- nosetests -s -v