language: c

os:
- osx
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    sudo apt-get update;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    brew update;
  fi

install:
- sudo pip install -r ./python/requirements.txt

script: 
- python setup.py build_ext --inplace
- nosetests -s -v
