language: python

python:
- "2.7"
- "3.4"

before_install:
- sudo apt-get update
- sudo apt-get -y install libmumps-seq-dev coinor-libclp-dev coinor-libcbc-dev

install: 
- pip install -r requirements.txt

script:
- python setup.py build_ext --inplace --with mumps clp cbc
- nosetests -s -v
- python -c "import optalg; optalg.lin_solver.LinSolverMUMPS();"
- ls /usr/lib | grep mumps
- ls /usr/lib/x86_64-linux-gnu/ | grep Clp