language: python

install: 
- sudo apt-get update
- sudo apt-get -y install libmumps-seq-dev
- sudo pip install nose numpy scipy cython dill

script:
- python setup.py build_ext --inplace --no_ipopt
- nosetests -s -v